#!/usr/bin/env python3
"""
Analyze whether the sign error exists in both old and new implementations.
"""

def analyze_old_vs_new_implementation():
    """Analyze if the sign error exists in both old and new implementations."""
    print("🔍 ANALYZING OLD VS NEW IMPLEMENTATION")
    print("=" * 80)
    
    print("📋 IMPLEMENTATION ANALYSIS:")
    print("-" * 50)
    
    print("🔴 OLD METHOD:")
    print("  - Uses: utils.generate_sentence_replacements_with_nebius()")
    print("  - Calls: differentially_private_replacement() from dp_sanitizer.py")
    print("  - Same exponential mechanism as new method")
    print()
    
    print("🔵 NEW METHOD:")
    print("  - Uses: utils.generate_sentence_replacements_with_nebius_diverse()")
    print("  - Calls: differentially_private_replacement() from dp_sanitizer.py")
    print("  - Same exponential mechanism as old method")
    print()
    
    print("🎯 KEY FINDING:")
    print("-" * 50)
    print("BOTH old and new methods use the SAME exponential mechanism!")
    print("They both call differentially_private_replacement() from dp_sanitizer.py")
    print()
    
    print("📊 EVIDENCE FROM TEST SCRIPTS:")
    print("-" * 50)
    print("In test_epsilon_comparison_scaled.py:")
    print("  Line 135: from dp_sanitizer import differentially_private_replacement")
    print("  Line 137: old_perturbed = differentially_private_replacement(...)")
    print("  Line 161: new_perturbed = differentially_private_replacement(...)")
    print()
    print("Both methods use the EXACT SAME function!")
    print()
    
    print("🔍 WHAT'S DIFFERENT BETWEEN OLD AND NEW:")
    print("-" * 50)
    print("OLD METHOD:")
    print("  - generate_sentence_replacements_with_nebius()")
    print("  - 5 API calls × 10 candidates = 50 candidates")
    print("  - Same prompt for all API calls")
    print()
    print("NEW METHOD:")
    print("  - generate_sentence_replacements_with_nebius_diverse()")
    print("  - 5 API calls × 20 candidates = 100 candidates")
    print("  - Different prompts targeting different similarity ranges")
    print()
    print("🎯 THE EXPONENTIAL MECHANISM IS IDENTICAL!")
    print()
    
    print("🚨 IMPLICATIONS:")
    print("-" * 50)
    print("1. ✅ The sign error affects BOTH old and new methods equally")
    print("2. ✅ Both methods have the same epsilon sensitivity problem")
    print("3. ✅ The diversity improvement in new method is real (better candidates)")
    print("4. ❌ But both methods still have the backwards epsilon behavior")
    print()
    
    print("📊 WHY NEW METHOD SHOWS BETTER DIVERSITY:")
    print("-" * 50)
    print("The new method generates more diverse candidates:")
    print("  - Targets different similarity ranges (0.1-0.9)")
    print("  - Uses 5 different prompts for different abstraction levels")
    print("  - Generates 100 candidates vs 50 in old method")
    print()
    print("But the exponential mechanism still has the sign error:")
    print("  - P(candidate) ∝ exp(epsilon * similarity)")
    print("  - Higher epsilon → Higher similarity (backwards!)")
    print()
    
    print("🔧 THE FIX:")
    print("-" * 50)
    print("Fix the sign error in dp_sanitizer.py line 58:")
    print("  Change: p_unnorm = np.exp(-epsilon * distances)")
    print("  To:     p_unnorm = np.exp(epsilon * distances)")
    print()
    print("This will fix BOTH old and new methods simultaneously!")
    print()
    
    print("📈 EXPECTED RESULTS AFTER FIX:")
    print("-" * 50)
    print("OLD METHOD (after fix):")
    print("  - Still limited diversity (50 candidates)")
    print("  - But epsilon will work correctly")
    print("  - ε=0.5 → low similarity, ε=2.0 → high similarity")
    print()
    print("NEW METHOD (after fix):")
    print("  - Better diversity (100 candidates)")
    print("  - Epsilon will work correctly")
    print("  - ε=0.5 → low similarity, ε=2.0 → high similarity")
    print("  - Should show much better epsilon sensitivity")
    print()
    
    print("🎯 SUMMARY:")
    print("-" * 50)
    print("1. ❌ Sign error exists in BOTH old and new methods")
    print("2. ✅ New method has better candidate diversity")
    print("3. 🔧 Fix the sign error in dp_sanitizer.py")
    print("4. 🎯 Both methods will then work correctly")
    print("5. 📈 New method should show much better epsilon sensitivity")

if __name__ == "__main__":
    analyze_old_vs_new_implementation()

